=== Django Application

For truly testing metrics and logging, this section cover building a basic tool kit application using Django. The application will include a package that provides Django middlewares to monitor the application with Prometheus and how to create a custom metric.

==== Start project

This guide is done using Red Hat Enterprise Linux 8 as the client operating system, create a new working directory:

[source%nowrap]
----
mkdir django-toolkit && cd django-toolkit
----

Create a new Python Virtual Environment and activate it:

[source%nowrap]
----
python3.8 -m venv venv
source venv/bin/activate
----

Upgrade `pip` and install `django`:

[source%nowrap]
----
pip install --upgrade pip
pip install django
----

Start a new Django project, migrat the initial database changes and run the local test server:

[source%nowrap]
----
django-admin startproject configuration .
python manage.py migrate
python manage.py runserver
----

==== Monitoring App


[source%nowrap]
----
python manage.py startapp monitoring
----


Add the new `monitoring` app to installed apps in `settings.py`:


[source%nowrap]
----
vi configuration/settings.py
----

[source%nowrap,python]
----
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitoring',
]
----


==== Templates


Add a project level templates directory in `settings.py`:

[source%nowrap]
----
vi config/settings.py
----

[source%nowrap,python]
----
TEMPLATES = [
    {
        ...
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        ...
    },
]
----

Create the directory and templates:

[source%nowrap]
----
mkdir templates
touch templates/_base.html
touch templates/home.html
----

Edit the base template:


[source%nowrap]
----
vi templates/_base.html
----

[source%nowrap,html]
----
<!-- templates/_base.html -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Toolkit{% endblock title %}</title>
    </head>
    <body>
        <div class="continer">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>
----

Edit the monitoring page template:

[source%nowrap]
----
vi templates/monitoring.html
----

[source%nowrap,html]
----
<!-- templates/monitoring.html -->
{% extends '_base.html' %}

{% block title %}Monitoring{% endblock title %}

{% block content %}
    <h1>Monitoring</h1>
{% endblock content %}
----


==== URLs and View

Configure the site URLs:


[source%nowrap]
----
vi configuration/urls.py
----

[source%nowrap,python]
----
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('monitoring.urls')),
]
----

Add app URLs:

[source%nowrap]
----
vi monitoring/urls.py
----

[source%nowrap,python]
----
from django.urls import path
from .views import MonitoringPageView

urlpatterns = [
    path('', MonitoringPageView.as_view(), name='monitoring'),
]

----

Add app view:

[source%nowrap]
----
vi monitoring/views.py
----

[source%nowrap,python]
----
from django.views.generic import TemplateView


class MonitoringPageView(TemplateView):
    template_name = 'monitoring.html'
----

=== Django Prometheus

Install the `django-prometheus` package into the project:


[source%nowrap]
----
pip install django-prometheus
----

Include it in `settings.py` under `INSTALLED_APPS` and `MIDDLEWARE`:

[source%nowrap]
----
vi configuration/settings.py
----

[source%nowrap,python]
----
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitoring',
    'django_prometheus', # NEW
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware', # NEW
]
----

Update the projects `urls.py` to include `/metrics/`:

[source%nowrap]
----
vi configuration/urls.py
----

[source%nowrap,python]
----
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('monitoring.urls')),
    path('', include('django_prometheus.urls')),
]
----

==== Custom Metric

Installing `django-prometheus` also installs `prometheus-client`, for reference `pip install prometheus-client`.

This is the most basic example, adding two custom metrics, each has two functions to increment or get the value of a metric.


Add `metrics.py`:


[source%nowrap]
----
vi monitoring/metrics.py
----


[source%nowrap,python]
----
from prometheus_client import Counter

counter_one = Counter('arbitrary_counter_one', 'number of times button clicked')
counter_two = Counter('arbitrary_counter_two', 'number of times button clicked time two')


def increment_counter_one():
    counter_one.inc()


def get_current_counter_one_value():
    return counter_one._value.get()


def increment_counter_two():
    counter_two.inc(2)


def get_current_counter_two_value():
    return counter_two._value.get()

----

Update date the view to include the functions:

[source%nowrap]
----
vi monitoring/views.py
----


[source%nowrap,python]
----
from django.shortcuts import render
from django.views import View

from .metrics import increment_counter_one
from .metrics import increment_counter_two
from .metrics import get_current_counter_one_value
from .metrics import get_current_counter_two_value


class MonitoringPageView(View):

    def get(self, request):

        current_value_counter_one = get_current_counter_one_value()
        current_value_counter_two = get_current_counter_two_value()

        return render(request, 'monitoring.html', {'counter_one': current_value_counter_one,
                                                   'counter_two': current_value_counter_two})

    def post(self, request):

        action = self.request.POST['action']

        current_value_counter_one = get_current_counter_one_value()
        current_value_counter_two = get_current_counter_two_value()

        if action == 'metric_one':
            increment_counter_one()
            current_value_counter_one = get_current_counter_one_value()

        elif action == 'metric_two':
            increment_counter_two()
            current_value_counter_two = get_current_counter_two_value()

        return render(request, 'monitoring.html', {'counter_one': current_value_counter_one,
                                                   'counter_two': current_value_counter_two})
----

Update the template to include buttons and display the values, for example:

[source%nowrap,html]
----
<form method="POST">
{% csrf_token %}

<p>Custom Metric One Value: {{ counter_one }}</p>
<button class="uk-button uk-button-default" type="submit" name='action' value="metric_one">Increment</button>
</form>
----

==== On Demand Logging

To add a feature to write our to the logs on-demand, you can add a view in the same way, for example:

[source%nowrap,python]
----
import random

from django.shortcuts import render
from django.views import View

import datetime

import logging


class LoggerPageView(View):

    def get(self, request):
        return render(request, 'logger.html')

    def post(self, request):

        action = self.request.POST['action']

        if action == 'logger_one':
            now = datetime.datetime.now()
            formatedate = now.strftime("%Y-%m-%d %H:%M:%S")
            error_string = f'[{formatedate}] "ERROR" Status: 500 "Message from Logger:" Internal Server Error'
            logger = logging.getLogger(__name__)
            logger.error(error_string)
            return render(request, 'logger.html')

        if action == 'logger_two':
            number1 = random.randint(1000, 9999)
            number2 = random.randint(1000, 9999)
            now = datetime.datetime.now()
            formatedate = now.strftime("%Y-%m-%d %H:%M:%S")
            credit_card_string = f'[{formatedate}] "INFO" Status: 200 Customer Credit Card number 4321-4321-{number1}-{number2}'
            logger = logging.getLogger(__name__)
            logger.error(credit_card_string)
            return render(request, 'logger.html')
----

=== Django Toolkit

Here is my version of the tool for testing with: https://github.com/richardwalkerdev/django-toolkit

(Strictly for dev/test usage!!)


==== Podman

Add a `Dockerfile` this copies the code and bakes it into an image:

----
# Dockerfile

# FROM directive instructing base image to build upon
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Create and change to working dir
RUN mkdir /code
WORKDIR /code

# Install dependencies
COPY requirements.txt /code/
RUN pip install -r requirements.txt

# Copy code
COPY . /code/

# EXPOSE port 7000 to allow communication to/from server
EXPOSE 8000

# Database migrations
CMD python manage.py makemigrations
CMD python manage.py migrate

# CMD specifies the command to execute to start the server running.
CMD python manage.py runserver 0.0.0.0:8000
----


Build the image:

----
buildah bud -t richardwalker.dev/django-toolkit-img .
----

Run as container by creating a new pod  and mapping port `8000`:

----
podman run --name django-toolkit -dt --pod new:toolkit-pod -p 8000:8000 richardwalker.dev/django-toolkit-img
----

http://127.0.0.1:8000

If needed, save the container image to file:

----
podman save -o django-toolkit.tar richardwalker.dev/django-toolkit-img
----

This can be load again with:

----
podman load --input django-toolkit.tar
----


Images can be listed with:

----
podman images
----

